package com.quizbot.bot.dispatcher;

public enum UserState {
    IDLE,
    AWAITING_QUESTION_TEXT,
    AWAITING_CORRECT_ANSWER,
    AWAITING_INCORRECT_ANSWER_1,
    AWAITING_INCORRECT_ANSWER_2,
    AWAITING_INCORRECT_ANSWER_3,
    AWAITING_DIFFICULTY,
    AWAITING_CONFIRMATION,
    AWAITING_UPDATE_FIELD_CHOICE,
    AWAITING_UPDATE_NEW_VALUE,
    IN_QUIZ,
    AWAITING_SCORE_RESET_CONFIRMATION,
    AWAITING_GENERATION_TOPICS,
    AWAITING_GENERATION_DIFFICULTY,
    AWAITING_GENERATION_TIMEOUT_CONTINUE,
    AWAITING_GROUP_DELETE_CONFIRMATION
}
